### ISSUE TITLE
media synchronization failing after 6 minutes

### ISSUE THREAD

**Issue by skidda666** [mregni/EmbyStat#1007]
using Windows 2016 server edition and v0.2.0-beta.13 version of emby stat. Media synchronization will start and go through my files get about 80% then stop and give an error. here is the error log
[embystaterrorlog.txt](https://github.com/mregni/EmbyStat/files/3905824/embystaterrorlog.txt)

**Comment by PartTheSeas** [comment]
Same for me. Never got beyond show 1218/1530. I really crave for a stable release haha 😄 

Not able to get any data pulled into the db, sigh :(

**Comment by PartTheSeas** [comment]
Here are the logs, always error with show 1231, not 1218. Holy shute :D 

[2019-12-03.log](https://github.com/mregni/EmbyStat/files/3915796/2019-12-03.log)

**Comment by skidda666** [comment]
yeah, this is the second time this has happened to me, at first i just removed emby stat all together and then re 'installed' it, same result  =(

**Comment by PartTheSeas** [comment]
I removed the show in question (where the syncing stops) and will report in a few minutes whether this helped :) mregni pls see my logs. It seems like there's an exception with a duplicate key

**Comment by PartTheSeas** [comment]
Nope. Same error, only 1 show earlier =)

**Comment by mregni** [comment]
Hey guys, sorry I missed your issue a couple of days ago. 

Looks like the sync is failing because of shows that are in multiple libraries (I guess) so I will try that switch from insert to upsert meaning the duplicate errors should be gone.

There are also some other exceptions with date-time formats and null ref exception. I'll have a look at them as well asap.

**Comment by PartTheSeas** [comment]
Hey Mikhael! Thanks so much <3 I've been back to Emby from Plex for the bazillionth time and I'd love to see my stats haha. If I can help you with any debugging let me know! I'd love to see this working 💯

**Comment by mregni** [comment]
Thanks for the support! Development is going slow at the moment because of the steep learning curve :) And also because it's just a lot of work :p 

I'm preparing a fix for your issues mentioned and let you know asap when I have a build that you can test. Are you running on a win-x64 machine?

**Comment by PartTheSeas** [comment]
Hey regni. Very understandable, don't stress yourself! We're all patiently waiting for you <3 Great idea = Great patience! 💪 

Yes, I'm running an x64 Win10 :)

**Comment by mregni** [comment]
Oke, I'm changing some code around and then I'll post a nightly build here so you can test it out. Hopefully later today :)

**Comment by PartTheSeas** [comment]
Awwwwsum <3 Looking forward to it and have a great day <3

**Comment by mregni** [comment]
So, I created a new build you can test if you have the time. It's to large to upload here so I uploaded on transfernow. Hope it works!
https://transfernow.net/88g5k1k335gq 

It should be able to fixe the problems you guys are facing. Hope it works :D

**Comment by skidda666** [comment]
woohoo, i think we're in business finally got past the 80% mark and now its calculating movie stats and i got this little gem in the job logs feed  "18:53:23 03-12-19 MEDIASYNC-JOB => Removing shows that are no longer present on your server (if any)"

**Comment by PartTheSeas** [comment]
Yeehaw! Working now here too! <3<3 !

**Comment by PartTheSeas** [comment]
I'm sorry. It did process all TV shows now, but returns an error at the end again 😢 

[2019-12-04.log](https://github.com/mregni/EmbyStat/files/3919378/2019-12-04.log)

**Comment by mregni** [comment]
No problem, thanks for the logs! I'll get on it today and build you a new test version :)

**Comment by mregni** [comment]
@PartTheSeas, could you check issue #1017 for more information about fixing your bug?

**Comment by skidda666** [comment]
yeah same here, stopped right at 85% after syncing tv series and just stood at a stand still all night...hrm
can't seem to get a log file to pull as it is still synching...

**Comment by mregni** [comment]
Can you access the EmbyStat folder itself? If so, you can find your logs in the /config/Logs folder. 

Be aware that it will contain your emby server url so best is to send the logs via PM on [gitter](https://gitter.im/EmbyStat/Lobby) or on the [Emby forum](https://emby.media/community/index.php?/user/33776-reggi/)

**Comment by alfablac** [comment]
I get the same errors, particularly the LiteDB Exception

LiteDB.LiteException: Cannot insert duplicate key in unique index '_id'.

and I see @mregni is already informed of the bug, but anyways, in my case I use two paths to host my TV library... a local folder, which holds the recent episodes and a cloud drive mount, which holds the archive, both set in the same Emby Library ("TV"). I can see on Emby's metadata's editor I have two entries for all shows that have a entry on both folder paths, let's say /home/user/TV and /mnt/cloud/TV 

Maybe it could be useful for a test scenario. 

EDIT: That using debian beta 14 version. Weird is that an error on the ShowRepository occurs for all shows that have this setup, but this one below is the one that kills the syncjob

`   at LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, Byte level, IndexNode last)
   at LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteEngine.<>c__DisplayClass22_0.<Insert>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func'2 action)
   at LiteDB.LiteEngine.InsertBulk(String collection, IEnumerable'1 docs, Int32 batchSize, BsonType autoId)
   at EmbyStat.Repositories.ShowRepository.<>c__DisplayClass5_0.<UpsertShow>b__0() in /home/vsts/work/1/s/EmbyStat.Repositories/ShowRepository.cs:line 90
   at EmbyStat.Repositories.BaseRepository.ExecuteQuery(Action query) in /home/vsts/work/1/s/EmbyStat.Repositories/BaseRepository.cs:line 29
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.PerformShowSyncAsync(IReadOnlyList'1 showsThatNeedAnUpdate, Library library, DateTime updateStartTime) in /home/vsts/work/1/s/EmbyStat.Jobs/Jobs/Sync/MediaSyncJob.cs:line 264
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessShowsAsync(IEnumerable'1 libraries, CancellationToken cancellationToken) in /home/vsts/work/1/s/EmbyStat.Jobs/Jobs/Sync/MediaSyncJob.cs:line 202
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync() in /home/vsts/work/1/s/EmbyStat.Jobs/Jobs/Sync/MediaSyncJob.cs:line 85
   at EmbyStat.Jobs.BaseJob.Execute() in /home/vsts/work/1/s/EmbyStat.Jobs/BaseJob.cs:line 54
   at EmbyStat.Jobs.BaseJob.Execute() in /home/vsts/work/1/s/EmbyStat.Jobs/BaseJob.cs:line 66
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)`

**Comment by mregni** [comment]
Thanks for the extra scenario indeed! Currently, I created a fix but then it seems that EmbyStat is allocating episodes to shows that are not correct (Two and a half men episodes get inserted in the 90210 show for example)

**Comment by mregni** [comment]
Hey everyone, can you try running this new version with some extra logging?
~~Link removed~~
Use the new package in the download link below.

This should add a line to the log file for every episode as well for all seasons and shows so be aware that it can become very large with you have lots of episodes :) Feel free to share the log file with me so I can fix the issue faster.


Ow, it's maybe a good idea to run EmbyStat with the --no-updates flag so the updater will not trigger while running this nightly version (it has a lower version than the one on GitHub so auto-updater will try and update the server)

**Comment by alfablac** [comment]
Is it possible to compile one for Debian?

**Comment by mregni** [comment]
~~@alfablac, here you go: Link removed :)~~

Use the new package in the download link below

**Comment by alfablac** [comment]
Looks like episodes IDs are indeed messing with the insert in the DB.
Not sure if it's what you did in the extended log, but the IDs shown when throwing the error are found on another TV shows.
https://send.firefox.com/download/621c61a63fd5be83/#hjMm0md5QnJMMeMIsOQvoQ
(expires after 3 downloads / 1 day )

**Comment by mregni** [comment]
Thanks for the logs! I forgot to include the fix I already made for the duplicate keys.
I created some new nightly builds that would fix the duplicate key exceptions but should display when episodes are indeed mixed between shows.

Link with WIN and DEBIAN package: https://transfernow.net/18elp3h1anar

It is already a bit concerning that you have multiple Beyblade shows and they share the same first episode :s

**Comment by alfablac** [comment]
Weird indeed. Found out I saved separate folders for Beyblade G-Revolution (with S03E01, E02, etc inside it) and Beyblade V-Force (S02), TheTVDB considers than as seasons from Beyblade. 

On the metadata editor I found out Emby consider it as three separate shows with three entries of each season inside each show. lol
That makes 9 season entries (3 x 3 seasons) for 3 shows named Beyblade. lol

Will do a clean up on these folders and see if Embystat behave better.

Though Emby is still confused by the scenario of two folders (one local one in the cloud) -- it has the same behaviour of Beyblade. Multiple seasons inside two show entries.

EDIT: @mregni  I tested with the build you linked in the comment aboce (it went on my github email despite you removing it O.o). Not sure if you removed because it was unfinished or something, but finding shows works now, but it fails to calculate stats https://send.firefox.com/download/354472c93871217a/#-mHMitjsNT7ENyU7dQ0fjQ

**Comment by mregni** [comment]
Thanks for the logs!
Seems like it is running fine until the calculations.

Can you do a rerun with the new build? I added some extra logging while calculating the missing episodes. https://transfernow.net/18elp3h1anar 

As for the Bayblade issue. That would indeed kick EmbyStat out of balance because I expect a 1 to many relationship between a show and his episodes. And not that an episodes can have multiple shows as well. 

Anyway, that is not the problem with this issue because here EmbyStat fetches his episode list and for some reason also fetches an episode that is actually linked to a different show.

**Comment by alfablac** [comment]
@mregni 
https://send.firefox.com/download/5e47ffd2ae190a80/#EKjNTAnTczxuYezSRBjprg

**Comment by mregni** [comment]
After having a hard fight with my own code I think I fixed the duplicate key bug! If you want you can test it with version beta.15 that I just released.

The main problem was that I tried to insert the episode twice in my db, stupid mistake. But in the meantime, I also found some other bugs in the sync.
- Using the DVD season numbers from TVDB instead of aired.
- Merged duplicate shows when they are in the same library (merged on duplicate TVDB id), this can happen when you have a library with multiple hdd's and each hdd contains a portion of the same show. All these duplicate shows will be merged into one show.

I hope this helps!! If there are any problems still feel free to log a message.

Also, I noticed for libraries > 1000 shows the statistic calculation can take a long time (up to 20-30 minutes). I will have to do a lot of refactoring to decrease this to a more acceptable time.

**Comment by alfablac** [comment]
> After having a hard fight with my own code I think I fixed the duplicate key bug! If you want you can test it with version beta.15 that I just released.
> 
> The main problem was that I tried to insert the episode twice in my db, stupid mistake. But in the meantime, I also found some other bugs in the sync.
> 
> * Using the DVD season numbers from TVDB instead of aired.
> * Merged duplicate shows when they are in the same library (merged on duplicate TVDB id), this can happen when you have a library with multiple hdd's and each hdd contains a portion of the same show. All these duplicate shows will be merged into one show.
> 
> I hope this helps!! If there are any problems still feel free to log a message.
> 
> Also, I noticed for libraries > 1000 shows the statistic calculation can take a long time (up to 20-30 minutes). I will have to do a lot of refactoring to decrease this to a more acceptable time.

Fixed for me. Amazing job, thanks!
I could test more, but for now it's 'closable' for me.

**Comment by jaycedk** [comment]
I have just updated and all the errors are gone :)
Good job, you can close this for me.

**Comment by mregni** [comment]
Thanks for the response! Going to close the issue for now. If new duplicates pop up feel free to comment on this ticket.
