### ISSUE TITLE
Media sync fails

### ISSUE THREAD

**Issue by Nickbert7** [mregni/EmbyStat#105]
The media sync fails if I try to run the sync task.
Here is the log:
[log20180712.txt](https://github.com/mregni/EmbyStat/files/2189234/log20180712.txt)
Is there any data within the logs which I should delete or anonymize?

**Comment by mregni** [comment]
Ha this seems to be a new issue! I'll have a look when I get home

No, at this moment no personal data is logged. Mostly only guids are saved in the logs (database id's)

**Comment by mregni** [comment]
I was looking at your log file, at is seems then when EmbyStat collects the movies from your "Filme" collection Emby kills the connection. Can you maybe have a look at the Emby logs to see if there is an exception somewhere around the same time you performed the sync?

That would give us more information about why the API call is killed before receiving all data.

**Comment by Nickbert7** [comment]
I can't see any exception within the emby logs.
Here are the Emby debug logs and the EmbyStat logs:
[EmbyLog.txt](https://github.com/mregni/EmbyStat/files/2192827/EmbyLog.txt)
[log20180713.txt](https://github.com/mregni/EmbyStat/files/2192828/log20180713.txt)

**Comment by mregni** [comment]
Thanks for the logs! I'll contact Luke from Emby to ask what's happening here. Looks like I need to add something to my http call maybe. 

Will also check the Emby code to see where these strange lines in the logs is coming from

> 2018-07-13 15:30:47.606 Debug BaseItem: Query requires post-filtering due to CollapseBoxSetItems
2018-07-13 15:30:55.334 Debug BaseItem: Query requires post-filtering due to LinkedChildren. Type: BoxSet
2018-07-13 15:30:55.350 Debug BaseItem: Query requires post-filtering due to LinkedChildren. Type: BoxSet
2018-07-13 15:30:55.383 Debug BaseItem: Query requires post-filtering due to LinkedChildren. Type: BoxSet

**Comment by Nickbert7** [comment]
Just for your Information, today I tried to set up the stat server again and I was able to finish the sync task.
A few weeks ago I had deleted one of my movie libaries which might had caused the error.
