### ISSUE TITLE
TV shows menu does not appear

### ISSUE THREAD

**Issue by gundamboyzack** [mregni/EmbyStat#1296]
# Bug report

**Describe the bug**
No menu object for TV shows

**To Reproduce**
Add TV shows to library, no way to access the data on the side menu, and no way to modify under settings (also no listing)

**Expected behavior**
TV shows has an entry on the left menu like Movies does

**System (please complete the following information):**

- OS: Debian 10.4
- Browser Chrome
- Version 0.2.0-beta.22

**Comment by jaycedk** [comment]
TV shows will be added in the next release.

**Comment by mregni** [comment]
Thanks @jaycedk for replying. I have hidden the show pages because they are not ready in the new React frontend but I already wanted some feedback about the current state and layout. 

Shows will be added one of the next beta versions. 
Going to close this issue for now as it is not an issue or bug.
