### ISSUE TITLE
Updating Password non functional.

### ISSUE THREAD

**Issue by n00b42** [mregni/EmbyStat#1677]
In Settings/General using "New password" does not update the password.

Furthermore, the "old password" field should maybe be a non-plaintext field as well

**Comment by andyfore** [comment]
While I agree on the plaintext field issue, I disagree on the functionality.  I just performed a new installation, and I was able to get update my password through the webui with no issues.

**Comment by mregni** [comment]
I released beta.30 yesterday. Feel free to install the new version and see if this problem is not fixed.

The plain text issue is fixed as you can see in the screenshot below and for me the password udpate works as well.
![image](https://user-images.githubusercontent.com/22617019/168753293-fc5de1cb-e5da-4944-ae9c-96d82a5fa6d0.png)
