### ISSUE TITLE
linux data location switch

### ISSUE THREAD

**Issue by wvroger** [mregni/EmbyStat#853]
Great work!

can you add a data location switch for CLI launching

ie data=/opt/embystat/,,,,

as it is now you can not use a startup script because it is looking for config files in the wrong place.

**Comment by mregni** [comment]
Hi, thanks for posting this request.

I'm not really familiar with unix systems and what you are trying to do. You mean you need the location switch in the docker container? 

Should be nice to get EmbyStat running with a startup script! So feel free to point me in the correct direction to enable this. Or create a PR.

**Comment by mtompkins** [comment]
This systemd seems to work fine:

```
[Unit]
Description=Emby Server is a personal media server with apps on just about every device.
After=network.target

[Service]
EnvironmentFile=/etc/emby-server.conf
WorkingDirectory=/opt/emby-server
ExecStart=/opt/emby-server/bin/emby-server
RestartForceExitStatus=3
User=emby

[Install]
WantedBy=multi-user.target
```

**Comment by mregni** [comment]
Oke, so how do I add this to the project so other Ubuntu users can use this systemd?
Sorry for asking but I have only limited knowhow of Unix systems.

**Comment by mtompkins** [comment]
Because you pack up everything in a zip folder, and you don't use a more formal package manager for installation on Linux (like **apt** or **yay**), the "best" way IMO would be to add it to the bundle (perhaps in a folder for clarity). It would then be up to the Linux user to copy it to the proper location on the Linux box and enable it.

What I've shared is a **systemd** unit file.

Here is a little background: https://wiki.archlinux.org/index.php/Systemd
(certainly other sources of info on **systemd** available)

**Comment by mregni** [comment]
Well, the best thing to do is get it the correct way (using apt or yay) in the end. 

I did some quick research and found https://wiki.ubuntu.com/PackagingGuide/Basic https://launchpad.net/ and https://askubuntu.com/questions/16446/how-to-get-my-software-into-ubuntu so it should be possible to build and package EmbyStat the proper way for Ubuntu and Debian.

Thanks for the share! I'll have a closer look at the systemd docs as well.

**Comment by mtompkins** [comment]
A proper package for Linux distros is certainly the way to go but no easy task, especially for someone who doesn't spend their days in Linux.

Just a reference that may be helpful if you indeed head down that road...

https://github.com/jordansissel/fpm
https://fpm.readthedocs.io/en/latest/#

**Comment by mregni** [comment]
I use some Raspberry Pi's at home, but more with plug and play tools :) So it will be a fun adventure to get Embystat packages for various Linux distros. 

Thanks for the references!

**Comment by diedrichg** [comment]
What about adding a section in the settings to point to a data location. It would be a form input but with a button to browse the drive's directory structure - like Emby does with its metadata storage location.

**Comment by mregni** [comment]
At the end that would be a good idea yeah. That will take some time to implement because what happens when a user selects a path without a config file, with an invalid config file, where do I store that path because I can't save it in the config file itself anymore, ...

I created an issue (#894) to keep track of that change.

**Comment by rTiGd2** [comment]
You could just use /etc like everyone else, at least for an 'initial configuration' file that tells EmbyStat where it can find the real config/data/log locations?

As for systemd and .Net applications, that's always a pain because some of us don't want to run software under the 'default' name (my Emby doesn't run as user 'emby' for example and I have to run a post-install script to edit the systemd file for it) - Who knows, perhaps you can switch effective user/group in Mono these days?

**Comment by rTiGd2** [comment]
Perhaps you 'can' switch from an admin/root user to one with less destructive powers *insert manic laugh*

https://stackoverflow.com/questions/16138389/change-current-linux-user-in-a-c-sharp-application-running-with-mono

If this is possible, then you could create a systemd that starts as root but then checks config file to see what actual user/group is required and switches to it.

**Comment by mregni** [comment]
I'm not using Mono, so I have no idea if that solution is still working on .net CORE as well. 

As for the /etc file, can you give some example? I have almost no experience in unix systems at all :)

**Comment by mregni** [comment]
I found an interesting article about systemd configuration for .net core here https://github.com/tmds/Tmds.Systemd. Looks like I need to add some code to support it properly.

**Comment by rTiGd2** [comment]
Actually, I think I may look into using that library myself, it's actually quite nice. 

The main thing to remember with packaging on Linux is to ensure you do not over-write configuration files with new versions. There are a few ways to do this (look up information on creating rpmnew versions of such files for one example)

As for using /etc - It's just the 'standard' place to put configuration files in a Linux environment, so you could have, for example, /etc/embystat/main.config - In there you could have a set of 'default' configuration values. However, if /etc/embystat/user.config existed, you could take the values from main.config unless they were set in user.config.

For example

::main.config
log.directory.path=/var/log/embystat/
log.directory.format=YYYY-mm-dd-XXX
data.directory.path=/opt/embystat/data

::user.config
data.directory.path=/data/embystat/

So the two log variables are used from main but the data directory path is the one set in user.config. This way you can always have a baseline set of variables (and new additions are always set) but the user can change where these belong.

As for the systemd file, mine is this.

::/etc/systemd/system/embystat.service
```
[Unit]
Description=EmbyStat
After=network-online.target

[Service]
User=tig
Group=tig
WorkingDirectory=/opt/EmbyStat/
ExecStart=/opt/EmbyStat/EmbyStatStart
ExecStop=/opt/EmbyStat/EmbyStatStop
Type=simple
TimeoutStopSec=30
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```
The start and stop are two scripts I've written as it's good to have some way of 'gracefully' killing a process and allowing it to clean up than just blow it out of the water ;-)
Logging to journal (as with that library) isn't a terrible idea either.
