### ISSUE TITLE
Rename show collection tab

### ISSUE THREAD

**Issue by mregni** [mregni/EmbyStat#872]
![image](https://user-images.githubusercontent.com/22617019/62548858-c6ebdf80-b867-11e9-8593-c69f51af132d.png)

Header should ne called something else, "Episode overview" maybe?

**Comment by diedrichg** [comment]
Emby refers to groups of content (TV, movies, music) as "Libraries (Library)". Currently, "Collection" is misleading and, in the world of Emby, refers to a group of similar movies (Marvel Cinematic Universe, Indiana Jones, Back To The Future, etc.)

I think I commented on this "Collection" tab in another github issue. It's invisible. I don't even notice it when I'm looking at the page, it blends in. It needs to be moved or somehow stand out in another way. 

I agree that it needs to be more accurately descriptive. I think "TV Library", "Shows Overview", "Shows List" or some combination of those words would work better. 

Finally, I'm seeing some duplicates. I'm assuming these are leftover bits from long ago that are still in the Emby database - if we had links on this "TV Library" tab, then we could easily delete, or otherwise clean up our libraries.

**Comment by mregni** [comment]
Yeah, you mentioned it on the forum indeed. You are correct that it's not really visible at the moment. I have to work on some UI ideas to get it to stand out more. Not sure how yet.

I will, however, rename collections to library to get it more in line with Emby.
